# Generated by Django 3.2 on 2021-08-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20210802_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='settings.MEDIA_ROOT/profile/basic_profile.png', null=True, upload_to='profile/'),
        ),
    ]
