# Generated by Django 3.2 on 2021-08-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='media/profile/basic_profile.png', null=True, upload_to='profile/'),
        ),
    ]
