# Generated by Django 3.2 on 2021-08-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='profile/basic_profile.gif', upload_to='profile/'),
        ),
    ]
