# Generated by Django 3.2 on 2021-08-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_post', models.IntegerField()),
                ('writer', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('stars', models.IntegerField(default=0)),
                ('liked_users', models.TextField(blank=True, default='None,', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
