# Generated by Django 3.2 on 2021-08-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_seen', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=50)),
                ('image', models.ImageField(default='profile/basic_profile.png', upload_to='board/')),
                ('body', models.TextField()),
                ('category', models.CharField(max_length=10)),
                ('comments_count', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('stars', models.IntegerField(default=0)),
                ('liked_users', models.TextField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
