# Generated by Django 3.2 on 2021-08-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_posts_liked_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(default='board/image.png', upload_to='board/'),
        ),
    ]
