# Generated by Django 3.2 on 2021-08-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_posts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(default='board/image.gif', upload_to='board/'),
        ),
    ]
